import time
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

# =====================================================================
# 1. ENVIRONMENT LOAD & DATA PREPARATION
# =====================================================================
print("📦 Loading preprocessed datasets and artifacts...")

# Load the padded sequences and data generated by your preprocessing step
try:
    X = np.load("padded_sequences.npy")
    df = pd.read_csv("combined_preprocessed.csv")
except FileNotFoundError:
    print("⚠️ Preprocessed files not found locally, simulating upstream inputs...")
    X = np.random.randint(0, 30000, size=(198476, 80))
    classes = ['Bored', 'Confident', 'Confused', 'Curious', 'Frustrated']
    df = pd.DataFrame({'emotion': np.random.choice(classes, 198476)})

# CORRECTED LABEL ENCODING LOGIC
label_encoder = LabelEncoder()
if "emotion" in df:
    y = label_encoder.fit_transform(df["emotion"])
else:
    y = label_encoder.fit_transform(np.random.choice(['Bored', 'Confident', 'Confused', 'Curious', 'Frustrated'], 198476))

NUM_CLASSES = len(label_encoder.classes_)

# Train-Test Split (80% Train, 20% Validation)
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# =====================================================================
# 2. FOCAL LOSS FUNCTION DEFINITION
# =====================================================================
def focal_loss(gamma=2.0, alpha=0.25):
    def focal_loss_fixed(y_true, y_pred):
        y_true = tf.cast(y_true, tf.int32)
        y_true_one_hot = tf.one_hot(y_true, depth=NUM_CLASSES)
        
        epsilon = tf.keras.backend.epsilon()
        y_pred = tf.clip_by_value(y_pred, epsilon, 1.0 - epsilon)
        
        cross_entropy = -y_true_one_hot * tf.math.log(y_pred)
        loss = alpha * tf.math.pow(1.0 - y_pred, gamma) * cross_entropy
        return tf.math.reduce_sum(loss, axis=-1)
    return focal_loss_fixed

# =====================================================================
# 3. BILSTM MODEL ARCHITECTURE DESIGN
# =====================================================================
MAX_VOCAB_SIZE = 30000
EMBEDDING_DIM = 128
LSTM_UNITS = 128
MAX_SEQ_LEN = 80

model = Sequential([
    Embedding(input_dim=MAX_VOCAB_SIZE, output_dim=EMBEDDING_DIM, mask_zero=True),
    Bidirectional(LSTM(units=LSTM_UNITS, dropout=0.2, use_bias=False)), 
    Dense(128, activation="relu"),
    Dropout(0.3),
    Dense(NUM_CLASSES, activation="softmax")
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3, clipnorm=1.0),
    loss=focal_loss(gamma=2.0, alpha=0.25),
    metrics=["accuracy"]
)

# Display structural overview summary table
model.summary()

# =====================================================================
# 4. TRAINING CALLBACKS CONFIGURATION
# =====================================================================
callbacks = [
    EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True),
    ReduceLROnPlateau(monitor="val_loss", patience=2, factor=0.5)
]

# =====================================================================
# 5. EXECUTE TRAINING RUN
# =====================================================================
print("\n🚀 Training (balanced + focal)...")
start = time.time()

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=10,
    batch_size=512,
    callbacks=callbacks,
    verbose=1
)

print(f"\n⏰ Training time: {((time.time() - start) / 60):.2f} min")

# =====================================================================
# 6. CLASSIFICATION MODEL EVALUATION
# =====================================================================
print("\n📊 EVALUATION")
y_pred_probs = model.predict(X_val, verbose=0)
y_pred = np.argmax(y_pred_probs, axis=1)

print("\nCLASSIFICATION REPORT")
print(classification_report(y_val, y_pred, target_names=label_encoder.classes_, digits=4))

print("\n🔮 Prediction distribution:")
print(pd.Series(y_pred).value_counts(normalize=True))